// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project_MusicPlayer

#include "ui.h"
#include <Music.h>
lv_obj_t *ui_list1;
lv_obj_t *ui_list1_btn;
lv_obj_t *ui_listCloseBtn;    // 关闭按钮
lv_obj_t *ui_listPrevBtn;     // 上一页按钮
lv_obj_t *ui_listNextBtn;     // 下一页按钮
lv_obj_t *ui_listPageLabel;   // 页码信息标签

// 播放列表分页相关变量
const int ITEMS_PER_PAGE = 20;   // 每页显示20首
int currentPage = 0;             // 当前显示的页码（从0开始）
int totalPages = 0;              // 总页数

// 前向声明
static void prevPage();
static void nextPage();
static void closePlayList(lv_event_t *e);

void PauseClicke(lv_event_t *e)
{
	lv_img_set_angle(ui_citou, -200); // 磁头旋转到停止位
	lv_anim_del_all();				  // 删除所有动画
	pause_status = 1;				  // 手动暂停标志位
	Music_Pause();					  // 暂停播放音乐
	lv_label_set_text(ui_Label2, "暂停播放");
}

void PlayClicked(lv_event_t *e)
{
	lv_img_set_angle(ui_citou, map(Music_GetCurrentPlayTime(), 0, duration, 60, -60)); // 设置磁头转动角度
	HaibaoXuanzhuan_Animation(ui_haibao, 0);
	pause_status = 0; // 手动暂停标志位取消
	Music_Play();
	lv_label_set_text(ui_Label2, "正在播放");
}

void NextClicke(lv_event_t *e)
{
	Music_Next();
	if (pause_status) // 如果处于暂停状态，还保存暂停状态，只更新曲目信息
	{
		Music_Pause();
		String fileName = musicFiles[music_i];
		// 去掉路径，只保留文件名
		int lastSlash = fileName.lastIndexOf("/");
		if (lastSlash != -1)
		{
			fileName = fileName.substring(lastSlash + 1);
		}
		// 去掉扩展名
		int dotIndex = fileName.lastIndexOf(".");
		if (dotIndex != -1)
		{
			fileName = fileName.substring(0, dotIndex);
		}
		currentTitle = fileName;
		lv_label_set_text(ui_Label2, "暂停播放");
		lv_label_set_text(ui_MusicTitleLabel, currentTitle.c_str()); //  歌曲名
	}
}

void PlayModeClicked(lv_event_t *e)
{
	switchPlayMode();

	switch (currentPlayMode)
	{
	case SINGLE_LOOP:
		lv_imgbtn_set_src(ui_PlayModeButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_single_loop_png, NULL);
		lv_imgbtn_set_src(ui_PlayModeButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_single_loop_png, NULL);
		lv_label_set_text(ui_Label2, "正在播放/单曲循环");
		break;
	case LIST_LOOP:
		lv_imgbtn_set_src(ui_PlayModeButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_list_loop_png, NULL);
		lv_imgbtn_set_src(ui_PlayModeButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_list_loop_png, NULL);
		lv_label_set_text(ui_Label2, "正在播放/目录循环");
		break;
	case RANDOM_PLAY:
		lv_imgbtn_set_src(ui_PlayModeButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_random_play_png, NULL);
		lv_imgbtn_set_src(ui_PlayModeButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_random_play_png, NULL);
		lv_label_set_text(ui_Label2, "正在播放/随机播放");
		break;

	default:
		break;
	}

	Serial.println(currentPlayMode);
}

void VolumeClicked(lv_event_t *e)
{
	// 1、获取音量值

	// 2、音量值显示到滑块
	lv_slider_set_value(ui_VolumeSlider, getVolume(), LV_ANIM_OFF);
}

void VolumeValueChange(lv_event_t *e)
{
	// 1. 获取事件目标对象（滑块）
	lv_obj_t *slider = lv_event_get_target(e);

	// 2. 获取当前滑块值
	int32_t volume = lv_slider_get_value(slider);
	setVolume(volume);
}

void PrevClicked(lv_event_t *e)
{
	Music_Prev();
	if (pause_status)
	{
		Music_Pause();
		String fileName = musicFiles[music_i];
		// 去掉路径，只保留文件名
		int lastSlash = fileName.lastIndexOf("/");
		if (lastSlash != -1)
		{
			fileName = fileName.substring(lastSlash + 1);
		}
		// 去掉扩展名
		int dotIndex = fileName.lastIndexOf(".");
		if (dotIndex != -1)
		{
			fileName = fileName.substring(0, dotIndex);
		}
		currentTitle = fileName;
		lv_label_set_text(ui_Label2, "暂停播放");
		lv_label_set_text(ui_MusicTitleLabel, currentTitle.c_str()); //  歌曲名
	}
}

/*播放列表曲目点击回调函数；点击曲目后播放列表中的曲目*/
static void ui_event_list1_handler(lv_event_t *e)
{
	lv_event_code_t code = lv_event_get_code(e);
	lv_obj_t *obj = lv_event_get_target(e);

	if (code == LV_EVENT_CLICKED)
	{
		// 从按钮的用户数据中获取索引
		size_t index = (size_t)lv_obj_get_user_data(obj);
		if (index >= fileCount)
		{
			return;
		}
		
		// 从 musicFiles 数组中获取完整路径
		String fullPath = musicFiles[index];
		Music_PlayPath(fullPath.c_str());
		music_prev_i = music_i;				   // 保存上一首播放的曲目索引
		music_i = index;						   // 直接设置当前播放的曲目索引

		Serial.println(music_prev_i);
		Serial.println(music_i);
		
		// 保存播放状态
		savePlayState();
		
		// 关闭播放列表
		closePlayList(NULL);
		pause_status = 0;									 // 手动暂停标志位取消
	}
}

// 清空列表所有项
static void clearListItems()
{
	if (ui_list1 == NULL) return;
	
	// 删除列表的所有子对象
	lv_obj_clean(ui_list1);
}

// 加载指定页码的内容
static void loadPage(int page)
{
	if (page < 0 || page >= totalPages || ui_list1 == NULL)
	{
		return;
	}
	
	// 清空当前页面
	clearListItems();
	
	// 计算起始和结束索引
	int startIndex = page * ITEMS_PER_PAGE;
	int endIndex = min(startIndex + ITEMS_PER_PAGE, fileCount);
	
	// 加载这一页的内容
	for (int i = startIndex; i < endIndex; i++)
	{
		if (i < 0 || i >= fileCount) continue;
		
		/*取消路径和.mp3后缀*/
		String fullPath = musicFiles[i];
		String displayName = fullPath;
		// 去掉路径，只保留文件名
		int lastSlash = displayName.lastIndexOf("/");
		if (lastSlash != -1)
		{
			displayName = displayName.substring(lastSlash + 1);
		}
		// 去掉扩展名
		int dotIndex = displayName.lastIndexOf(".");
		if (dotIndex != -1)
		{
			displayName = displayName.substring(0, dotIndex);
		}

		ui_list1_btn = lv_list_add_btn(ui_list1, NULL, displayName.c_str());
		// 高亮当前播放的歌曲
		if (i == music_i)
		{
			lv_obj_set_style_text_color(ui_list1_btn, lv_color_hex(0xff0000), LV_PART_MAIN | LV_STATE_DEFAULT);
		}
		else
		{
			lv_obj_set_style_text_color(ui_list1_btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
		}
		lv_obj_set_style_bg_opa(ui_list1_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
		lv_obj_set_style_text_font(ui_list1_btn, &ui_font_MengYuanHeiTi_12, LV_PART_MAIN | LV_STATE_DEFAULT);
		lv_obj_set_style_text_align(ui_list1_btn, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);

		// 绑定点击事件并存储索引到用户数据
		lv_obj_set_user_data(ui_list1_btn, (void *)(size_t)i);
		lv_obj_add_event_cb(ui_list1_btn, ui_event_list1_handler, LV_EVENT_CLICKED, NULL);
	}
	
	// 更新页码信息标签
	if (ui_listPageLabel != NULL)
	{
		lv_label_set_text_fmt(ui_listPageLabel, "曲目(%d/%d)-第(%d/%d)页", 
			music_i + 1, fileCount, currentPage + 1, totalPages);
	}
	
	Serial.printf("已加载第 %d/%d 页\n", page + 1, totalPages);
}

// 上一页
static void prevPage()
{
	if (currentPage > 0)
	{
		currentPage--;
		loadPage(currentPage);
	}
}

// 下一页
static void nextPage()
{
	if (currentPage < totalPages - 1)
	{
		currentPage++;
		loadPage(currentPage);
	}
}

// 关闭播放列表
static void closePlayList(lv_event_t *e)
{
	if (ui_list1 != NULL)
	{
		lv_obj_del(ui_list1);
		ui_list1 = NULL;
	}
	if (ui_listCloseBtn != NULL)
	{
		lv_obj_del(ui_listCloseBtn);
		ui_listCloseBtn = NULL;
	}
	if (ui_listPrevBtn != NULL)
	{
		lv_obj_del(ui_listPrevBtn);
		ui_listPrevBtn = NULL;
	}
	if (ui_listNextBtn != NULL)
	{
		lv_obj_del(ui_listNextBtn);
		ui_listNextBtn = NULL;
	}
	if (ui_listPageLabel != NULL)
	{
		lv_obj_del(ui_listPageLabel);
		ui_listPageLabel = NULL;
	}
}

/*播放列表按钮点击回调函数*/
void PlayListButtonClicked(lv_event_t *e)
{
	lv_label_set_text_fmt(ui_Label1, "播放列表（%d/%d）", music_i + 1, fileCount);
	
	// 隐藏原本UI自带的播放列表面板
	lv_obj_add_flag(ui_caidanPanel, LV_OBJ_FLAG_HIDDEN);
	
	// 关闭所有旧的UI元素
	closePlayList(NULL);

	// 计算总页数
	totalPages = (fileCount + ITEMS_PER_PAGE - 1) / ITEMS_PER_PAGE;
	
	// 计算当前应该显示哪一页（包含当前播放的歌曲）
	currentPage = music_i / ITEMS_PER_PAGE;
	
	// 检查边界
	if (currentPage >= totalPages) currentPage = totalPages - 1;
	if (currentPage < 0) currentPage = 0;

	// 创建关闭按钮（左上角）
	ui_listCloseBtn = lv_btn_create(lv_scr_act());
	lv_obj_set_size(ui_listCloseBtn, 30, 18);
	lv_obj_set_pos(ui_listCloseBtn, 0, 20);
	lv_obj_set_style_bg_color(ui_listCloseBtn, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_bg_opa(ui_listCloseBtn, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_radius(ui_listCloseBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_border_width(ui_listCloseBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
	
	lv_obj_t *closeLabel = lv_label_create(ui_listCloseBtn);
	lv_label_set_text(closeLabel, "X");
	lv_obj_center(closeLabel);
	lv_obj_set_style_text_color(closeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
	
	lv_obj_add_event_cb(ui_listCloseBtn, closePlayList, LV_EVENT_CLICKED, NULL);

	// 创建上一页按钮（关闭按钮右边）
	ui_listPrevBtn = lv_btn_create(lv_scr_act());
	lv_obj_set_size(ui_listPrevBtn, 30, 18);
	lv_obj_set_pos(ui_listPrevBtn, 30, 20);
	lv_obj_set_style_bg_color(ui_listPrevBtn, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_bg_opa(ui_listPrevBtn, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_radius(ui_listPrevBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_border_width(ui_listPrevBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
	
	lv_obj_t *prevLabel = lv_label_create(ui_listPrevBtn);
	lv_label_set_text(prevLabel, "<");
	lv_obj_center(prevLabel);
	lv_obj_set_style_text_color(prevLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
	
	lv_obj_add_event_cb(ui_listPrevBtn, [](lv_event_t *e){ prevPage(); }, LV_EVENT_CLICKED, NULL);

	// 创建下一页按钮（上一页按钮右边）
	ui_listNextBtn = lv_btn_create(lv_scr_act());
	lv_obj_set_size(ui_listNextBtn, 30, 18);
	lv_obj_set_pos(ui_listNextBtn, 60, 20);
	lv_obj_set_style_bg_color(ui_listNextBtn, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_bg_opa(ui_listNextBtn, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_radius(ui_listNextBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_border_width(ui_listNextBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
	
	lv_obj_t *nextLabel = lv_label_create(ui_listNextBtn);
	lv_label_set_text(nextLabel, ">");
	lv_obj_center(nextLabel);
	lv_obj_set_style_text_color(nextLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
	
	lv_obj_add_event_cb(ui_listNextBtn, [](lv_event_t *e){ nextPage(); }, LV_EVENT_CLICKED, NULL);

	// 创建页码信息标签（下一页按钮右边）
	ui_listPageLabel = lv_label_create(lv_scr_act());
	lv_obj_set_pos(ui_listPageLabel, 95, 22);
	lv_label_set_text_fmt(ui_listPageLabel, "曲目(%d/%d) 第(%d/%d)页", 
		music_i + 1, fileCount, currentPage + 1, totalPages);
	lv_obj_set_style_text_color(ui_listPageLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui_listPageLabel, &ui_font_MengYuanHeiTi_12, LV_PART_MAIN | LV_STATE_DEFAULT);
	// 设置黑色背景，和播放列表背景一致
	lv_obj_set_style_bg_color(ui_listPageLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_bg_opa(ui_listPageLabel, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_pad_top(ui_listPageLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_pad_bottom(ui_listPageLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_pad_left(ui_listPageLabel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_pad_right(ui_listPageLabel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

	// 创建全屏播放列表容器
	ui_list1 = lv_list_create(lv_scr_act());
	lv_obj_set_size(ui_list1, 240, 282);  // 全屏大小（减去顶部状态栏20px和控制栏18px）
	lv_obj_set_pos(ui_list1, 0, 38);  // 从控制栏下方开始
	lv_obj_set_align(ui_list1, LV_ALIGN_TOP_LEFT);

	// 设置半透明黑色背景
	lv_obj_set_style_bg_color(ui_list1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_bg_opa(ui_list1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_border_width(ui_list1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_radius(ui_list1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

	// 禁止列表滚动
	lv_obj_clear_flag(ui_list1, LV_OBJ_FLAG_SCROLLABLE);

	// 加载当前页
	loadPage(currentPage);
	
	Serial.printf("播放列表初始化完成，共 %d 页，当前显示第 %d 页\n", totalPages, currentPage + 1);
}