// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project_MusicPlayer

#include "ui.h"
#include <Music.h>
#include "freertos/task.h"

// 播放列表页面涉及「新建一整套界面」的重操作，这里打印 LVGL 内存池与任务栈余量，
// 用于区分「内存耗尽」与「死锁/卡住」两类故障。
static void plLogMem(const char *tag)
{
	lv_mem_monitor_t mon;
	lv_mem_monitor(&mon);
	Serial.printf("[PL] %s | lv_mem free=%u biggest=%u used=%u%% frag=%u%% | heap=%u | stack_watermark=%u\n",
				  tag, (unsigned)mon.free_size, (unsigned)mon.free_biggest_size,
				  (unsigned)mon.used_pct, (unsigned)mon.frag_pct,
				  (unsigned)esp_get_free_heap_size(),
				  (unsigned)uxTaskGetStackHighWaterMark(NULL));
}

// 前向声明
static void plClose(lv_event_t *e);
static void plPrevPage(lv_event_t *e);
static void plNextPage(lv_event_t *e);
static void plPlayItem(lv_event_t *e);

// 播放列表页（独立 screen，打开时销毁主播放界面以节省资源）
static lv_obj_t *ui_playListScreen = nullptr;
static lv_obj_t *ui_plList = nullptr;      // 曲目列表
static lv_obj_t *ui_plPageLabel = nullptr; // 页码信息

const int ITEMS_PER_PAGE = 20; // 每页显示 20 首
static int plPage = 0;         // 当前页码（从 0 开始）
static int plTotalPages = 0;   // 总页数

void PauseClicke(lv_event_t *e)
{
	// 磁头（唱针）组件已移除，暂停/播放不再需要转动唱针
	pause_status = 1; // 手动暂停标志位
	Music_Pause();	  // 暂停播放音乐
	lv_label_set_text(ui_Label2, "暂停播放");
}

void PlayClicked(lv_event_t *e)
{
	// 磁头（唱针）组件已移除，播放时不再计算唱针角度
	// 封面为静态显示，不再启动旋转动画（详见 main.cpp 中的说明）
	pause_status = 0; // 手动暂停标志位取消
	Music_Play();
	lv_label_set_text(ui_Label2, "正在播放");
}

void NextClicke(lv_event_t *e)
{
	Music_Next();
	if (pause_status) // 如果处于暂停状态，还保存暂停状态，只更新曲目信息
	{
		Music_Pause();
		String fileName = musicFiles[music_i];
		// 去掉路径，只保留文件名
		int lastSlash = fileName.lastIndexOf("/");
		if (lastSlash != -1)
		{
			fileName = fileName.substring(lastSlash + 1);
		}
		// 去掉扩展名
		int dotIndex = fileName.lastIndexOf(".");
		if (dotIndex != -1)
		{
			fileName = fileName.substring(0, dotIndex);
		}
		currentTitle = fileName;
		lv_label_set_text(ui_Label2, "暂停播放");
		lv_label_set_text(ui_MusicTitleLabel, currentTitle.c_str()); //  歌曲名
	}
}

void PlayModeClicked(lv_event_t *e)
{
	switchPlayMode();

	switch (currentPlayMode)
	{
	case SINGLE_LOOP:
		lv_imgbtn_set_src(ui_PlayModeButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_single_loop_png, NULL);
		lv_imgbtn_set_src(ui_PlayModeButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_single_loop_png, NULL);
		lv_label_set_text(ui_Label2, "正在播放/单曲循环");
		break;
	case LIST_LOOP:
		lv_imgbtn_set_src(ui_PlayModeButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_list_loop_png, NULL);
		lv_imgbtn_set_src(ui_PlayModeButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_list_loop_png, NULL);
		lv_label_set_text(ui_Label2, "正在播放/目录循环");
		break;
	case RANDOM_PLAY:
		lv_imgbtn_set_src(ui_PlayModeButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_random_play_png, NULL);
		lv_imgbtn_set_src(ui_PlayModeButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_random_play_png, NULL);
		lv_label_set_text(ui_Label2, "正在播放/随机播放");
		break;

	default:
		break;
	}

	Serial.println(currentPlayMode);
}

void VolumeClicked(lv_event_t *e)
{
	// 1、获取音量值

	// 2、音量值显示到滑块
	lv_slider_set_value(ui_VolumeSlider, getVolume(), LV_ANIM_OFF);
}

void VolumeValueChange(lv_event_t *e)
{
	// 1. 获取事件目标对象（滑块）
	lv_obj_t *slider = lv_event_get_target(e);

	// 2. 获取当前滑块值
	int32_t volume = lv_slider_get_value(slider);
	setVolume(volume);
}

void PrevClicked(lv_event_t *e)
{
	Music_Prev();
	if (pause_status)
	{
		Music_Pause();
		String fileName = musicFiles[music_i];
		// 去掉路径，只保留文件名
		int lastSlash = fileName.lastIndexOf("/");
		if (lastSlash != -1)
		{
			fileName = fileName.substring(lastSlash + 1);
		}
		// 去掉扩展名
		int dotIndex = fileName.lastIndexOf(".");
		if (dotIndex != -1)
		{
			fileName = fileName.substring(0, dotIndex);
		}
		currentTitle = fileName;
		lv_label_set_text(ui_Label2, "暂停播放");
		lv_label_set_text(ui_MusicTitleLabel, currentTitle.c_str()); //  歌曲名
	}
}

/*==================== 播放列表页 ====================*/

// 取文件名（去掉路径与扩展名）用于列表显示
static String plDisplayName(const String &path)
{
	String name = path;
	int lastSlash = name.lastIndexOf("/");
	if (lastSlash != -1)
	{
		name = name.substring(lastSlash + 1);
	}
	int dotIndex = name.lastIndexOf(".");
	if (dotIndex != -1)
	{
		name = name.substring(0, dotIndex);
	}
	return name;
}

// 加载指定页
static void plLoadPage(int page)
{
	if (ui_plList == nullptr || plTotalPages <= 0)
	{
		return;
	}
	if (page < 0)
	{
		page = 0;
	}
	if (page >= plTotalPages)
	{
		page = plTotalPages - 1;
	}
	plPage = page;

	lv_obj_clean(ui_plList);

	int startIndex = page * ITEMS_PER_PAGE;
	int endIndex = startIndex + ITEMS_PER_PAGE;
	if (endIndex > fileCount)
	{
		endIndex = fileCount;
	}

	for (int i = startIndex; i < endIndex; i++)
	{
		lv_obj_t *btn = lv_list_add_btn(ui_plList, NULL, plDisplayName(musicFiles[i]).c_str());
		lv_obj_set_style_text_font(btn, &ui_font_AlibabaPuHuiTi_12, LV_PART_MAIN | LV_STATE_DEFAULT);
		lv_obj_set_style_text_align(btn, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);
		lv_obj_set_style_bg_opa(btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
		// 高亮当前播放曲目
		lv_obj_set_style_text_color(btn, lv_color_hex(i == music_i ? 0xFF4040 : 0xFFFFFF),
									LV_PART_MAIN | LV_STATE_DEFAULT);
		lv_obj_set_user_data(btn, (void *)(size_t)i);
		lv_obj_add_event_cb(btn, plPlayItem, LV_EVENT_CLICKED, NULL);
	}

	if (ui_plPageLabel != nullptr)
	{
		lv_label_set_text_fmt(ui_plPageLabel, "第%d/%d页", plPage + 1, plTotalPages);
	}

	Serial.printf("播放列表：第 %d/%d 页\n", plPage + 1, plTotalPages);
}

// 上一页
static void plPrevPage(lv_event_t *e)
{
	if (plPage > 0)
	{
		plLoadPage(plPage - 1);
	}
}

// 下一页
static void plNextPage(lv_event_t *e)
{
	if (plPage < plTotalPages - 1)
	{
		plLoadPage(plPage + 1);
	}
}

// 点击曲目：切歌并返回主播放界面
static void plPlayItem(lv_event_t *e)
{
	lv_obj_t *obj = lv_event_get_target(e);
	size_t index = (size_t)lv_obj_get_user_data(obj);
	if (index >= (size_t)fileCount)
	{
		return;
	}

	music_prev_i = music_i;
	music_i = (int)index;
	Music_PlayPath(musicFiles[index].c_str());
	savePlayState();
	pause_status = 0; // 手动暂停标志位取消
	// 列表选曲是明确的「我要听这首」动作，同时取消暂停意图，
	// 否则上一首的暂停会被带过来，看起来就像「选了但没反应」。
	Music_WantPaused(false);

	plClose(NULL);
}

// 关闭列表页：重建主播放界面并销毁列表页
static void plClose(lv_event_t *e)
{
	// 顺序非常重要：必须先重建并切换主界面，最后才删除列表页。
	// 原因：lv_disp_load_scr() 内部（lv_scr_load_anim）会对「当前活动屏幕」调用
	// lv_obj_set_pos(lv_scr_act(), 0, 0)。若先把活动屏幕（列表页）删掉，
	// lv_scr_act() 会返回已释放的野指针，随后解引用 NULL 直接崩溃
	// （LoadProhibited, EXCVADDR 0x20）。
	ui_Screen1_screen_init();
	lv_disp_load_scr(ui_Screen1);

	if (ui_playListScreen != nullptr)
	{
		// 当前正处于列表页内按钮的回调中，使用异步删除，
		// 避免在 LVGL 事件处理过程中释放事件所属对象
		lv_obj_del_async(ui_playListScreen);
		ui_playListScreen = nullptr;
	}
	ui_plList = nullptr;
	ui_plPageLabel = nullptr;
	plPage = 0;
	plTotalPages = 0;

	// 通知主循环重新应用界面状态
	UI_NotifyScreenRebuilt();
}

// 创建一个小按钮
static lv_obj_t *plMakeButton(lv_obj_t *parent, const char *text, int x, int w, lv_event_cb_t cb)
{
	lv_obj_t *btn = lv_btn_create(parent);
	lv_obj_set_size(btn, w, 22);
	lv_obj_set_pos(btn, x, 3);
	lv_obj_set_style_radius(btn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_border_width(btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_bg_color(btn, lv_color_hex(0x1F5C7A), LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_bg_opa(btn, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_add_event_cb(btn, cb, LV_EVENT_CLICKED, NULL);

	lv_obj_t *label = lv_label_create(btn);
	lv_label_set_text(label, text);
	lv_obj_set_style_text_font(label, &ui_font_AlibabaPuHuiTi_12, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_center(label);
	return btn;
}

/*播放列表按钮点击回调：新开播放列表页面，并销毁主播放界面*/
void PlayListButtonClicked(lv_event_t *e)
{
	if (ui_playListScreen != nullptr)
	{
		return; // 已经打开
	}

	plTotalPages = (fileCount + ITEMS_PER_PAGE - 1) / ITEMS_PER_PAGE;
	if (plTotalPages < 1)
	{
		plTotalPages = 1;
	}
	plPage = (fileCount > 0) ? (music_i / ITEMS_PER_PAGE) : 0;
	if (plPage >= plTotalPages)
	{
		plPage = plTotalPages - 1;
	}

	plLogMem("打开列表页: 进入");

	// 目标对象即将被销毁，先停掉正在运行的动画（如海报旋转）
	lv_anim_del_all();

	ui_playListScreen = lv_obj_create(NULL);
	lv_obj_clear_flag(ui_playListScreen, LV_OBJ_FLAG_SCROLLABLE);
	lv_obj_set_style_bg_color(ui_playListScreen, lv_color_hex(0x0B283D), LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_bg_opa(ui_playListScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

	// 顶部工具栏：返回 / 上一页 / 下一页 / 页码
	plMakeButton(ui_playListScreen, "返回", 3, 54, plClose);
	plMakeButton(ui_playListScreen, "上一页", 62, 56, plPrevPage);
	plMakeButton(ui_playListScreen, "下一页", 122, 56, plNextPage);

	ui_plPageLabel = lv_label_create(ui_playListScreen);
	lv_obj_set_pos(ui_plPageLabel, 184, 8);
	lv_obj_set_style_text_font(ui_plPageLabel, &ui_font_AlibabaPuHuiTi_12, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_color(ui_plPageLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

	// 曲目列表
	ui_plList = lv_list_create(ui_playListScreen);
	lv_obj_set_size(ui_plList, 240, 292);
	lv_obj_set_pos(ui_plList, 0, 28);
	lv_obj_set_style_radius(ui_plList, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_border_width(ui_plList, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_bg_color(ui_plList, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_bg_opa(ui_plList, 160, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_pad_all(ui_plList, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

	plLogMem("打开列表页: 框架就绪");

	plLoadPage(plPage);

	plLogMem("打开列表页: 列表已填充");

	// 先切到列表页，确认切换完成后再销毁主播放界面（节省内存与刷新开销）
	// 必须保持「先切换、后删除」：删除活动屏幕会让 lv_scr_act() 变成野指针
	lv_disp_load_scr(ui_playListScreen);
	if (ui_Screen1 != nullptr)
	{
		// 当前正处于 ui_Screen1 内按钮的回调中，异步删除更安全
		lv_obj_del_async(ui_Screen1);
		ui_Screen1 = nullptr;
	}

	plLogMem("打开列表页: 完成");
}
